server:
  applicationContextPath: /api
  applicationConnectors:
    - type: http
      port: 8080
datasource:
  driverClass: org.postgresql.Driver
  user: postgres
  password: password
  url: jdbc:postgresql://localhost:5432/postgres
